name: Rich
markdown: kramdown
github_username: richryan
baseurl: ""
url: ""

# Add excerpt separator
# Include this in long posts that need to be separated
excerpt_separator: <!--more-->

gems:
  # - jekyll-feed
  - jemoji
  - json
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  events:
    output: true
    permalink: /events/:path/
    title: Events
