name: Rich
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  extensions: fenced_code_blocks
#   syntax_highlighter_opts:
#         # Use existing pygments syntax highlighting css
#         css_class: 'highlight'
github_username: richryan
baseurl: ""
url: ""

# Add excerpt separator
# Include this in long posts that need to be separated
excerpt_separator: <!--more-->

# Allow posts in the future
future: true

exclude:
  - _ipynb

gems:
  # - jekyll-feed
  - jemoji
  - jekyll-scholar
  - rouge
  # - json
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  events:
    output: true
    permalink: /events/:path/
    title: Events

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  # source: ./_bibliography
  source: ./
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  use_raw_bibtex_entry: true

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
