name: Rich
highlighter: rouge
markdown: kramdown
# Note: To change the syntax coloring choose one of the styles
# that can be viewed with the command
# > rougify help style
# Put one of these styles into syntax.css; e.g.,
# > rougify style monokai > syntax.css
# (Note: this command must be issued in the directory where syntax.css is
# or the command must put the path where syntax.css is.)
# The file head.html links to syntax.css, so the highlighting is included in the
# html code automatically.
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  extensions: fenced_code_blocks
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
github_username: richryan
baseurl: ""
url: ""

# Add excerpt separator
# Include this in long posts that need to be separated
excerpt_separator: <!--more-->

# Allow posts in the future
future: true

exclude:
  - _ipynb

gems:
  # - jekyll-feed
  - jemoji
  - jekyll-scholar
  - rouge
  # - json
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  events:
    output: true
    permalink: /events/:path/
    title: Events

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  # source: ./_bibliography
  source: ./
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  use_raw_bibtex_entry: true

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
