name: Rich
markdown: kramdown
github_username: richryan
baseurl:

# gems:
#   - jekyll-feed
#   # - github-pages
# exclude:
#   - Gemfile
#   - Gemfile.lock

collections:
  events:
    output: true
    permalink: /events/:path/
    title: Events
